### PR TITLE
Support proxy settings

### LINKED ISSUE #82: Unable to use a proxy
Hello,

I found no way to tell this api to use a proxy to reach iyzico servers.

I would like to be able to provide the proxy settings (host, port ~~, username, password~~) so that the HTTPClient might be able to open a connection using the proxy

### PR DESCRIPTION
**Pull request by sporniket**
Content : 

* fixes #82 : Unable to use a proxy

### CODE REVIEW

**Comment by sporniket** [comment]
IyziLinkTest fails because link creation fails (status "failure", data is `null`), please fix this test : 

```
Running com.iyzipay.functional.IyziLinkTest
com.iyzipay.model.iyzilink.IyziLinkSaveResource@7f77e91b[
  data=<null>
  status=failure
  errorCode=100001
  errorMessage=Sistem hatası
  errorGroup=<null>
  locale=tr
  systemTime=1544542919719
  conversationId=<null>
]
com.iyzipay.model.iyzilink.IyziLinkPagingResource@29f69090[
  data=<null>
  status=failure
  errorCode=100001
  errorMessage=Sistem hatası
  errorGroup=<null>
  locale=tr
  systemTime=1544542921063
  conversationId=<null>
]
Tests run: 5, Failures: 2, Errors: 3, Skipped: 0, Time elapsed: 3.888 sec <<< FAILURE! - in com.iyzipay.functional.IyziLinkTest
should_create_iyziLink(com.iyzipay.functional.IyziLinkTest)  Time elapsed: 0.385 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[success]> but was:<[failure]>
	at com.iyzipay.functional.IyziLinkTest.should_create_iyziLink(IyziLinkTest.java:40)
should_retrieve_iyziLinks_with_pagination(com.iyzipay.functional.IyziLinkTest)  Time elapsed: 1.336 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[success]> but was:<[failure]>
	at com.iyzipay.functional.IyziLinkTest.should_retrieve_iyziLinks_with_pagination(IyziLinkTest.java:114)
should_delete_iyziLink(com.iyzipay.functional.IyziLinkTest)  Time elapsed: 0.723 sec  <<< ERROR!
java.lang.NullPointerException
	at com.iyzipay.functional.IyziLinkTest.should_delete_iyziLink(IyziLinkTest.java:177)
should_update_iyziLink(com.iyzipay.functional.IyziLinkTest)  Time elapsed: 0.699 sec  <<< ERROR!
java.lang.NullPointerException
	at com.iyzipay.functional.IyziLinkTest.should_update_iyziLink(IyziLinkTest.java:64)
should_retrieve_iyziLink_with_token(com.iyzipay.functional.IyziLinkTest)  Time elapsed: 0.741 sec  <<< ERROR!
java.lang.NullPointerException
	at com.iyzipay.functional.IyziLinkTest.should_retrieve_iyziLink_with_token(IyziLinkTest.java:137)
```

**Comment by pvtmert** [comment]
Hi there, have you tried using system proxy before? because setting java environment variables `java.net.useSystemProxies` to `true` then proper `http.proxyHost` and `http.proxyPort` should do without needing any external code.

some open proxy from internet: `159.65.105.99:3128`

simply doing:
```
java -Djava.net.useSystemProxies=true -Dhttp.proxyHost=159.65.105.99 -Dhttp.proxyPort=3128 YourEntryPoint
```
does the trick

here is my test code:

```java
public class Test {
	public static void main(String args[]) {
		try {
			HttpURLConnection.setFollowRedirects(true);
			HttpURLConnection connection = (HttpURLConnection) new URL("http://wtfismyip.com/text").openConnection();
			InputStream stream = connection.getInputStream();
			byte[] bytes = new byte[stream.available()];
			System.out.println("length:" + bytes.length + "\t" + stream.read(bytes));
			System.out.println("proxy:" + connection.usingProxy());
			System.out.println("bytes:" + new String(bytes));
		} catch (Exception e) {
			e.printStackTrace(System.err);
		}
		return;
	}
}
```

here is the output of invocation:

```
root@mert:/tmp# java Test
length:14	14
proxy:false
bytes:188.166.13.50

root@mert:/tmp# java -Djava.net.useSystemProxies=true -Dhttp.proxyHost=159.65.105.99 -Dhttp.proxyPort=3128 Test
length:26	26
proxy:true
bytes:2604:a880:2:d0::20cd:c00f
```

**Comment by sporniket** [comment]
@pvtmert yes, the proxy is not defined at the jvm level for security reasons. (e.g. we had to fix a potential security threat through XML parsing (Xml External Entity), but the variant that pings an external url would not work because the jvm is not aware of the proxy)

**Comment by sporniket** [comment]
Hello, is there a schedule to merge this pull request ?

**Comment by sporniket** [comment]
For the time being, I made available this modified version : 

```xml
<!-- https://mvnrepository.com/artifact/com.sporniket.iyzico/iyzipay-java -->
<dependency>
    <groupId>com.sporniket.iyzico</groupId>
    <artifactId>iyzipay-java</artifactId>
    <version>2.0.61</version>
</dependency>
```

**Comment by yyenigun** [comment]
We make backward compatibility tests on our sandbox environment. After the tests we would like to merge this pull request.

**Comment by sporniket** [comment]
Hello, I just noticed that the master branche had been updated.

I have rebased and updated my pull request.

I hope you will be able to merge soon.

Regards.

**Review by gulcabuk — APPROVED** [review]

**Pull request merged**
